### ISSUE TITLE
Add the wiki link to the markup-messages.

### ISSUE THREAD

**Issue by janniksam** [cake-contrib/Cake.Issues.InspectCode#128]
Just an idea I had:

The issue could have an link to the wiki at the start of each message.
The new format could be: "{ID}: {Message}". And the ID could be a link to the wikipage, if there is one in the xml.

**Comment by pascalberger** [comment]
What is your use case for this?

I don't think adding additional metadata to the message in an issue provider is the way to go. This would be a violation of separation of concerns. `IIssue` should contain the individual metadata provided by issue providers and let the consumer (reporting format, pullrequest implementation or any Cake build script) take care of the formatting.

If for example the InspectCode issue provider starts to use a custom format for the message, which not only contains the message, this would mean that for reporting formats or pull requests implementations there is no way anymore to get to the pure message. The Azure DevOps pull request implementation for example already adds the rule id with a link to the rule url to the begin of the message. In this case it would end with `{rule} {identifier} {message}` with rule and identifier both being a link to the wiki page and identifier and message both being the message.

**Comment by janniksam** [comment]
Ahh, I didnt know, it was already done by the PR implementations. My bad :/
