### ISSUE TITLE
Suggested Changes of Cake.Recipe 2.2.0

### ISSUE THREAD

**Issue by eoehen** [cake-contrib/Cake.Issues.InspectCode#171]
**Suggested Changes of Cake.Recipe 2.2.0:**

- Use embedded icon for NuGet package
- Add CakeContrib.Guidelines Nuget Package
- Remove usage of nuspec file(s) for NuGet packages
- Add Cake.Addin.Analyzer package
- Add settings.json file for VSCode

[Cake.Recipe migration documentation](https://cake-contrib.github.io/Cake.Recipe/docs/upgrading/1.x-to-2.x)

**Comment by pascalberger** [comment]
Closed since obsolete with https://github.com/cake-contrib/Cake.Issues/pull/414
