### ISSUE TITLE
Allow to retrieve issue provider type name without context

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.InspectCode#85]
There's currently a Cake alias property for retrieving the name of the issue provider type (`InspectCodeIssuesProviderTypeName`). This requires a Cake context and there might be situations where no context is available. There should be a way to retrieve the issue provider type name without requiring a context.

**Comment by janniksam** [comment]
This will be fixed possible with https://github.com/cake-contrib/Cake.Issues/issues/213 / https://github.com/cake-contrib/Cake.Issues/pull/218
